### ISSUE TITLE
Adding a "super-compact" view option

### ISSUE THREAD

**Issue by jburns12** [mitre/attack-navigator#11]
This would allow users to select a "super-compact" view of the matrix that consists solely of small rectangular boxes (colored as appropriate) without any labels for either tactics or techniques.

**Comment by thatfiferguy** [comment]
This feature has been implemented in [features/super-compact-view](https://github.com/mitre/attack-navigator/tree/features/super-compact-view) and merged into the develop branch.

The new view is referred to in the documentation as the "mini" view. Since there are now more than two views, the layer format was updated to v1.1 to accommodate the replacement of the _viewFullTable_ (boolean) field with a new _viewMode_ (number) field.
