### ISSUE TITLE
Associating user-defined metadata with techniques

### ISSUE THREAD

**Issue by rjsmitre** [mitre/attack-navigator#22]
Consider supporting the ability for users to associate arbitrary name-value pairs with a technique in a layer in addition to the existing metadata such as score, manually-assigned colors, comments, etc.

**Comment by cvantine** [comment]
Would be very useful to define metadata to show up on hover, as comments do now.

**Comment by isaisabel** [comment]
Feature implemented in [feature/user-defined-metadata](https://github.com/mitre/attack-navigator/tree/feature/user-defined-metadata) and merged into develop. The optional field `metadata` (which should be an array of objects of the format `{"name": string, "value": string}`) can now be added to the layer itself as well as individual techniques inside of the layer. This addition constitutes layer format version 2.1, which is fully backwards compatible with layer format version 2.0.

Metadata on the layer is editable inside of the "layer information" menu, however metadata on techniques is not currently editable due to the complexity of editing metadata when multiple techniques are selected. 

Metadata on techniques shows up in tooltips.
